language: node_js
node_js:
- '10'

jobs:
  allow_failures:
    - env: CAN_FAIL=true
  include:
    - stage: deploy
      install:
      - ./travis/install.sh
      script: ./travis/deploy.sh
    - stage: test
      install:
      - ./travis/install.sh
      - npm ci
      script: ./travis/test.sh
    - stage: pipelinetest
      install:
      - ./travis/install.sh
      - npm ci
      env: CAN_FAIL=true
      script: ./travis/pipelientest.sh  
    - stage: algorithmtest
      install:
      - ./travis/install.sh
      - npm ci
      env: CAN_FAIL=true
      script: ./travis/algorithmtest.sh
    - stage: algorithmBuild
      install:
      - ./travis/install.sh
      - npm ci
      env: CAN_FAIL=true
      script: ./travis/algorithmBuild.sh       
stages:
  - deploy
  - test
  - pipelientest
  - algorithmtest
  
