global:
  production: true
  clusterName: test
  registry: ""
  storage:
    binary: true
    fs:
      pvc: 
         name: 'hkube-storage'
         capacity: '50Gi'
         nfs_server: '172.20.46.223'
         nfs_root: '/nfs/storageclass/test-spot'
      base_directory: '/hkubedata'
  ingress:
    use_regex: true
    # hostname: ${CICD_HOSTNAME}
env:
  default_storage: 'fs'
build_secret:
  docker_registry: ''
  docker_namespace: ''
  docker_username: ${DOCKER_BUILD_PUSH_USERNAME}
  docker_password: ${DOCKER_BUILD_PUSH_PASSWORD}
etcd:
  persistentVolume:
    enabled: true
    storageClass: etcd-sc
task_executor:
  env:
    pipeline_drivers_amount: 30
monitor_server:
  env:
    elasticsearch_service_url: 'http://elasticsearch-ingest.logging.svc.test:9200'
storage_cleaner:
  pattern: "0 5 * * * "
etcd_cleaner:
  pattern: "0 5 * * * "
jaeger:
  enable: true  
