modified: 1688943168578
name: 0lAzCLWk
nodes:
  - nodeName: green
    algorithmName: eval-alg
    input:
      - '#@flowInput.inp'
    kind: algorithm
  - nodeName: yellow
    algorithmName: yellow-alg
    input:
      - '#@green.0'
    includeInResults: false
    kind: algorithm
  - nodeName: black
    algorithmName: black-alg
    input:
      - '@yellow'
    kind: algorithm
options:
  ttl: 3600
  batchTolerance: 80
  progressVerbosityLevel: info
triggers:
  pipelines:
    - simple2
kind: batch
experimentName: main
priority: 3
