# This is a basic workflow to help you get started with Actions

name: hkubectl-only

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  HkubeCliTests:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - name: create kubeconfig
        run: |
          echo "$KUBE_CONFIG_DATA" | base64 --decode > /tmp/config
          echo KUBECONFIG=/tmp/config >> $GITHUB_ENV
        env:
          KUBE_CONFIG_DATA: ${{ secrets.TEST_KUBECONFIG }}
      - name: create hkubectl
        run: |
          ./travis/cli.sh
          echo $PWD >> $GITHUB_PATH 
        env:
          KUBE_CONFIG_DATA: ${{ secrets.TEST_KUBECONFIG }}
          HKUBE_URL: ${{ secrets.HKUBE }}
      - name: test
        run:  |       
          npm run cliTests
        env:
          BASE_URL: https://${{ secrets.TEST_KUBERNETES_MASTER_IP }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_MASTER_URL }}
          KUBE_CONFIG_DATA: ${{ secrets.TEST_KUBECONFIG }}
          KEYCLOAK_DEV_PASS: ${{ secrets.KEYCLOAK_DEV_PASS }}
          KEYCLOAK_DEV_USER: ${{ secrets.KEYCLOAK_DEV_USER }}
          K8S_VERSION: 1.13
          K8S_CONFIG_PATH: /tmp/config
