# This is a basic workflow to help you get started with Actions

name: WindowsCli

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:    
  WindowsCli:
    runs-on: windows-latest
    timeout-minutes: 60
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - name: create kubeconfig
        run: |
          mkdir  d:\tmp 
          echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          echo "$KUBE_CONFIG_DATA" >> d:\tmp\config64.b64
          certutil -decode d:\tmp\config64.b64 d:\tmp\config
          echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          echo KUBECONFIG=d:/tmp/config >> $GITHUB_ENV
        env:
          KUBE_CONFIG_DATA: ${{ secrets.TEST_KUBECONFIG }}
          HKUBE_URL: ${{ secrets.HKUBE }}
      - name: create hkubectl
        run: |
          Invoke-WebRequest -OutFile d:\tmp\hkubectl.exe -Uri https://github.com/kube-HPC/hkubectl/releases/download/v1.1.61/hkubectl-win.exe
          d:\tmp\hkubectl.exe config set endpoint https://test.hkube.io
          d:\tmp\hkubectl.exe config set rejectUnauthorized false
          echo ~~~~~~~~~~~~~
          d:\tmp\hkubectl --version
          d:\tmp\hkubectl algorithm get green-alg --json
          echo ~~~===========
          echo "d:\tmp" >> $GITHUB_PATH 
        env:
          KUBE_CONFIG_DATA: ${{ secrets.TEST_KUBECONFIG }}
          HKUBE_URL: ${{ secrets.HKUBE }}
      - name: test
        run:  |       
          npm run cliTests
        env:
          HKUBE_URL: ${{ secrets.HKUBE }}
          BASE_URL: https://${{ secrets.TEST_KUBERNETES_MASTER_IP }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_MASTER_URL }}
          KUBE_CONFIG_DATA: ${{ secrets.TEST_KUBECONFIG }}
          K8S_VERSION: 1.13
          K8S_CONFIG_PATH: /tmp/config
  
